import { EnterpriseRequest } from '../src/types';

export const seedRequests: EnterpriseRequest[] = [
  {
    id: 'REQ-2026-101',
    employeeName: 'Rajesh Subramanian Kumar',
    employeeId: 'EMP-2026-005',
    department: 'Engineering & Operations',
    branch: 'NEOM Site Office',
    jobTitle: 'Heavy Excavator Operator',
    category: 'HR',
    requestType: 'Leave Request',
    requestDate: '2026-06-20',
    currentLevel: 3,
    currentLevelName: 'Level 3 – Human Resources Department',
    currentApprover: 'Sarah Khalid Al-Ghamdi (HR Mgr)',
    status: 'Pending Approval',
    priority: 'High',
    pendingDays: 5,
    slaLimitHours: 48,
    isFinancial: false,
    valueSAR: 0,
    details: 'Requesting 30 days of annual vacation starting Sep 1st to visit family in India.',
    submissionDate: '2026-06-20',
    lastActionDate: '2026-06-22',
    history: [
      { level: 1, levelName: 'Level 1 – Direct Supervisor', approverName: 'Ahmed Faraj Al-Dossary', action: 'Approved', date: '2026-06-21', comment: 'Operations schedule permits. Recommended.' },
      { level: 2, levelName: 'Level 2 – Department Manager', approverName: 'Tariq Abdulaziz Al-Otaibi', action: 'Approved', date: '2026-06-22', comment: 'Approved on operational ground.' }
    ],
    formData: {
      leaveType: 'Annual Leave',
      startDate: '2026-09-01',
      endDate: '2026-09-30',
      handoverTo: 'EMP-2026-006'
    }
  },
  {
    id: 'REQ-2026-102',
    employeeName: 'Faisal Ahmed Al-Harbi',
    employeeId: 'EMP-2026-004',
    department: 'Maintenance & Service',
    branch: 'Riyadh (HQ)',
    jobTitle: 'Senior Mechanic',
    category: 'Administrative',
    requestType: 'Attendance Adjustment',
    requestDate: '2026-06-24',
    currentLevel: 2,
    currentLevelName: 'Level 1 – Direct Supervisor',
    currentApprover: 'Ahmed Faraj Al-Dossary (Supervisor)',
    status: 'Pending Approval',
    priority: 'Medium',
    pendingDays: 1,
    slaLimitHours: 24,
    isFinancial: false,
    valueSAR: 0,
    details: 'Forgot to clock in on morning shift due to urgent emergency repair call-out at Site B.',
    submissionDate: '2026-06-24',
    lastActionDate: '2026-06-24',
    history: [],
    formData: {
      adjustmentDate: '2026-06-24',
      missingCheckIn: '08:00',
      reason: 'Urgent crane maintenance call-out'
    }
  },
  {
    id: 'REQ-2026-103',
    employeeName: 'Sajid Mahmood',
    employeeId: 'EMP-2026-008',
    department: 'Construction Operations',
    branch: 'Jeddah',
    jobTitle: 'Welder',
    category: 'Payroll',
    requestType: 'Overtime Request',
    requestDate: '2026-06-21',
    currentLevel: 3,
    currentLevelName: 'Level 2 – Department Manager',
    currentApprover: 'Bandar Al-Ghamdi (Project Manager)',
    status: 'Pending Approval',
    priority: 'Low',
    pendingDays: 4,
    slaLimitHours: 48,
    isFinancial: true,
    valueSAR: 1450,
    details: 'Overtime compensation request for 12 hours of night shift concrete joint reinforcement welding.',
    submissionDate: '2026-06-21',
    lastActionDate: '2026-06-22',
    history: [
      { level: 1, levelName: 'Level 1 – Direct Supervisor', approverName: 'Ahmed Faraj Al-Dossary', action: 'Approved', date: '2026-06-22', comment: 'Welding completed under urgent deadline. Approved.' }
    ],
    formData: {
      overtimeHours: 12,
      overtimeRate: 1.5,
      dateCompleted: '2026-06-20'
    }
  },
  {
    id: 'REQ-2026-104',
    employeeName: 'Yousef Al-Otaibi',
    employeeId: 'EMP-2026-010',
    department: 'Fleet Maintenance',
    branch: 'Dammam',
    jobTitle: 'Safety Inspector',
    category: 'Payroll',
    requestType: 'Employee Loan',
    requestDate: '2026-06-18',
    currentLevel: 4,
    currentLevelName: 'Level 4 – Finance / Accountant',
    currentApprover: 'Mohammad Salem Al-Qahtani (Finance Dir)',
    status: 'Pending Approval',
    priority: 'Critical',
    pendingDays: 7,
    slaLimitHours: 48,
    isFinancial: true,
    valueSAR: 45000,
    details: 'Personal medical advance loan request with automatic monthly salary deductions of 3,750 SAR.',
    submissionDate: '2026-06-18',
    lastActionDate: '2026-06-21',
    history: [
      { level: 1, levelName: 'Level 1 – Direct Supervisor', approverName: 'Tariq Mahmood', action: 'Approved', date: '2026-06-19', comment: 'Recommended on compassionate medical grounds.' },
      { level: 2, levelName: 'Level 2 – Department Manager', approverName: 'Tariq Abdulaziz Al-Otaibi', action: 'Approved', date: '2026-06-20', comment: 'Supports employee stability.' },
      { level: 3, levelName: 'Level 3 – Human Resources Department', approverName: 'Sarah Khalid Al-Ghamdi', action: 'Approved', date: '2026-06-21', comment: 'Balances are clear. Forwarding to Finance.' }
    ],
    formData: {
      loanAmount: 45000,
      monthlyDeduction: 3750,
      installments: 12,
      reason: 'Medical emergency surgery support'
    }
  },
  {
    id: 'REQ-2026-105',
    employeeName: 'Adnan Al-Shehri',
    employeeId: 'EMP-2026-009',
    department: 'Engineering & Operations',
    branch: 'Riyadh (HQ)',
    jobTitle: 'Lead Civil Engineer',
    category: 'Payroll',
    requestType: 'Salary Advance',
    requestDate: '2026-06-23',
    currentLevel: 3,
    currentLevelName: 'Level 3 – Human Resources Department',
    currentApprover: 'Sarah Khalid Al-Ghamdi (HR Mgr)',
    status: 'Pending Approval',
    priority: 'Medium',
    pendingDays: 2,
    slaLimitHours: 48,
    isFinancial: true,
    valueSAR: 8000,
    details: 'Advance of 50% of monthly basic salary due to urgent housing lease payment.',
    submissionDate: '2026-06-23',
    lastActionDate: '2026-06-24',
    history: [
      { level: 1, levelName: 'Level 1 – Direct Supervisor', approverName: 'Tariq Abdulaziz Al-Otaibi', action: 'Approved', date: '2026-06-24', comment: 'Approved.' },
      { level: 2, levelName: 'Level 2 – Department Manager', approverName: 'Tariq Abdulaziz Al-Otaibi', action: 'Approved', date: '2026-06-24', comment: 'Approved.' }
    ],
    formData: {
      advanceAmount: 8000,
      deductionMonth: '2026-07'
    }
  },
  {
    id: 'REQ-2026-106',
    employeeName: 'John Michael Doe',
    employeeId: 'EMP-2026-007',
    department: 'Engineering & Operations',
    branch: 'NEOM Site Office',
    jobTitle: 'Lead Engineer',
    category: 'Administrative',
    requestType: 'Business Trip Request',
    requestDate: '2026-06-22',
    currentLevel: 6,
    currentLevelName: 'Level 5 – General Manager (Final Approval)',
    currentApprover: 'Tariq Abdulaziz Al-Otaibi (General Manager)',
    status: 'Pending Approval',
    priority: 'High',
    pendingDays: 3,
    slaLimitHours: 72,
    isFinancial: true,
    valueSAR: 3500,
    details: 'Business trip delegation to Riyadh HQ for NEOM structural board reviews and compliance audit.',
    submissionDate: '2026-06-22',
    lastActionDate: '2026-06-24',
    history: [
      { level: 1, levelName: 'Level 1 – Direct Supervisor', approverName: 'Ahmed Faraj Al-Dossary', action: 'Approved', date: '2026-06-22', comment: 'Crucial presentation.' },
      { level: 2, levelName: 'Level 2 – Department Manager', approverName: 'Tariq Abdulaziz Al-Otaibi', action: 'Approved', date: '2026-06-23', comment: 'Approved.' },
      { level: 3, levelName: 'Level 3 – Human Resources Department', approverName: 'Sarah Khalid Al-Ghamdi', action: 'Approved', date: '2026-06-24', comment: 'Flights and accommodation budget verified.' }
    ],
    formData: {
      destination: 'Riyadh HQ',
      startDate: '2026-07-05',
      durationDays: 4,
      transportNeeded: true,
      accommodationNeeded: true
    }
  },
  {
    id: 'REQ-2026-107',
    employeeName: 'Tariq Mahmood',
    employeeId: 'EMP-2026-012',
    department: 'Fleet Maintenance',
    branch: 'NEOM Site Office',
    jobTitle: 'Fleet Supervisor',
    category: 'Assets & Equipment',
    requestType: 'Asset Custody Request',
    requestDate: '2026-06-25',
    currentLevel: 2,
    currentLevelName: 'Level 1 – Direct Supervisor',
    currentApprover: 'Ahmed Faraj Al-Dossary (Supervisor)',
    status: 'Pending Approval',
    priority: 'Medium',
    pendingDays: 0,
    slaLimitHours: 24,
    isFinancial: false,
    valueSAR: 0,
    details: 'Requesting allocation of 1x Leica TS16 High-Precision Robotic Total Station for Site C excavation plotting.',
    submissionDate: '2026-06-25',
    lastActionDate: '2026-06-25',
    history: [],
    formData: {
      assetName: 'Leica TS16 Robotic Total Station',
      estimatedReturnDate: '2026-08-30'
    }
  },
  {
    id: 'REQ-2026-108',
    employeeName: 'Rajesh Subramanian Kumar',
    employeeId: 'EMP-2026-005',
    department: 'Engineering & Operations',
    branch: 'NEOM Site Office',
    jobTitle: 'Heavy Excavator Operator',
    category: 'Assets & Equipment',
    requestType: 'Vehicle Request',
    requestDate: '2026-06-24',
    currentLevel: 3,
    currentLevelName: 'Level 2 – Department Manager',
    currentApprover: 'John Michael Doe (Lead Engineer)',
    status: 'Pending Approval',
    priority: 'High',
    pendingDays: 1,
    slaLimitHours: 48,
    isFinancial: false,
    valueSAR: 0,
    details: 'Requesting 4x4 pickup truck assignment for remote site survey and shift rotation transport.',
    submissionDate: '2026-06-24',
    lastActionDate: '2026-06-24',
    history: [
      { level: 1, levelName: 'Level 1 – Direct Supervisor', approverName: 'Ahmed Faraj Al-Dossary', action: 'Approved', date: '2026-06-24', comment: 'Operator requires mobility.' }
    ],
    formData: {
      vehicleType: '4x4 Pickup Truck',
      justification: 'Remote site surveys at Sector 9'
    }
  },
  {
    id: 'REQ-2026-109',
    employeeName: 'Bandar Al-Ghamdi',
    employeeId: 'EMP-2026-011',
    department: 'Engineering & Operations',
    branch: 'Riyadh (HQ)',
    jobTitle: 'Project Manager',
    category: 'Assets & Equipment',
    requestType: 'Fuel Request',
    requestDate: '2026-06-25',
    currentLevel: 2,
    currentLevelName: 'Level 1 – Direct Supervisor',
    currentApprover: 'Tariq Abdulaziz Al-Otaibi (Supervisor)',
    status: 'Pending Approval',
    priority: 'High',
    pendingDays: 0,
    slaLimitHours: 24,
    isFinancial: true,
    valueSAR: 12400,
    details: 'Diesel fuel replenishment dispatch (5,000 Liters) for heavy generators operating at Riyadh Metro construction Sector 4.',
    submissionDate: '2026-06-25',
    lastActionDate: '2026-06-25',
    history: [],
    formData: {
      fuelVolumeLiters: 5000,
      fuelType: 'Diesel',
      machineryTarget: 'Heavy Generators Sector 4'
    }
  },
  {
    id: 'REQ-2026-110',
    employeeName: 'Faisal Ahmed Al-Harbi',
    employeeId: 'EMP-2026-004',
    department: 'Maintenance & Service',
    branch: 'Riyadh (HQ)',
    jobTitle: 'Senior Mechanic',
    category: 'Assets & Equipment',
    requestType: 'Maintenance Request',
    requestDate: '2026-06-23',
    currentLevel: 3,
    currentLevelName: 'Level 2 – Department Manager',
    currentApprover: 'Tariq Abdulaziz Al-Otaibi (Manager)',
    status: 'Pending Approval',
    priority: 'Critical',
    pendingDays: 2,
    slaLimitHours: 24,
    isFinancial: true,
    valueSAR: 8400,
    details: 'Emergency spare part procurement & maintenance of main boom telescoping hydraulic cylinders for Liebherr Crane LTM 1050.',
    submissionDate: '2026-06-23',
    lastActionDate: '2026-06-23',
    history: [
      { level: 1, levelName: 'Level 1 – Direct Supervisor', approverName: 'Ahmed Faraj Al-Dossary', action: 'Approved', date: '2026-06-23', comment: 'Crane out-of-service. Priority 1.' }
    ],
    formData: {
      equipmentId: 'EQ-CRN-LIE500',
      failureType: 'Hydraulic leakage',
      urgency: 'Emergency'
    }
  },
  {
    id: 'REQ-2026-111',
    employeeName: 'Sarah Khalid Al-Ghamdi',
    employeeId: 'EMP-2026-002',
    department: 'Human Resources',
    branch: 'Riyadh (HQ)',
    jobTitle: 'Manager',
    category: 'HR',
    requestType: 'Recruitment Request',
    requestDate: '2026-06-21',
    currentLevel: 6,
    currentLevelName: 'Level 5 – General Manager (Final Approval)',
    currentApprover: 'Tariq Abdulaziz Al-Otaibi (General Manager)',
    status: 'Pending Approval',
    priority: 'Medium',
    pendingDays: 4,
    slaLimitHours: 72,
    isFinancial: true,
    valueSAR: 15000,
    details: 'Urgent hiring recruitment post for 3x certified concrete lab technicians and 2x senior safety inspectors for Riyadh Metro project.',
    submissionDate: '2026-06-21',
    lastActionDate: '2026-06-23',
    history: [
      { level: 1, levelName: 'Level 1 – Direct Supervisor', approverName: 'Tariq Abdulaziz Al-Otaibi', action: 'Approved', date: '2026-06-21', comment: 'Workforce shortage critical.' },
      { level: 2, levelName: 'Level 2 – Department Manager', approverName: 'Tariq Abdulaziz Al-Otaibi', action: 'Approved', date: '2026-06-22', comment: 'Approved.' },
      { level: 3, levelName: 'Level 3 – Human Resources Department', approverName: 'Sarah Khalid Al-Ghamdi', action: 'Approved', date: '2026-06-23', comment: 'Budgets and headcount vacancy verified.' }
    ],
    formData: {
      recruitmentPositions: ['Concrete Lab Technician', 'Senior Safety Inspector'],
      headcount: 5,
      budgetSalarySAR: 3000
    }
  },
  {
    id: 'REQ-2026-112',
    employeeName: 'Faisal Ahmed Al-Harbi',
    employeeId: 'EMP-2026-004',
    department: 'Maintenance & Service',
    branch: 'Riyadh (HQ)',
    jobTitle: 'Senior Mechanic',
    category: 'HR',
    requestType: 'Training Request',
    requestDate: '2026-06-24',
    currentLevel: 3,
    currentLevelName: 'Level 2 – Department Manager',
    currentApprover: 'Tariq Abdulaziz Al-Otaibi (Manager)',
    status: 'Pending Approval',
    priority: 'Low',
    pendingDays: 1,
    slaLimitHours: 48,
    isFinancial: true,
    valueSAR: 2200,
    details: 'Enrolment request for high-capacity hydraulic troubleshooting training certification at Liebherr Training Center.',
    submissionDate: '2026-06-24',
    lastActionDate: '2026-06-24',
    history: [
      { level: 1, levelName: 'Level 1 – Direct Supervisor', approverName: 'Ahmed Faraj Al-Dossary', action: 'Approved', date: '2026-06-24', comment: 'Will greatly improve repair response.' }
    ],
    formData: {
      courseTitle: 'Liebherr LTM Hydraulic Certification',
      institution: 'Liebherr Saudi Training Center',
      durationDays: 5
    }
  },
  {
    id: 'REQ-2026-113',
    employeeName: 'Rajesh Subramanian Kumar',
    employeeId: 'EMP-2026-005',
    department: 'Engineering & Operations',
    branch: 'NEOM Site Office',
    jobTitle: 'Heavy Excavator Operator',
    category: 'HR',
    requestType: 'Employee Information Update',
    requestDate: '2026-06-25',
    currentLevel: 2,
    currentLevelName: 'Level 1 – Direct Supervisor',
    currentApprover: 'Ahmed Faraj Al-Dossary (Supervisor)',
    status: 'Pending Approval',
    priority: 'High',
    pendingDays: 0,
    slaLimitHours: 24,
    isFinancial: false,
    valueSAR: 0,
    details: 'Submission and verification of newly renewed Saudi driving license (Heavy Duty, Exp: 2036).',
    submissionDate: '2026-06-25',
    lastActionDate: '2026-06-25',
    history: [],
    formData: {
      fieldsToChange: ['drivingLicense'],
      drivingLicenseNewValue: 'Heavy Duty, Exp: 2036-06-15'
    }
  },
  {
    id: 'REQ-2026-114',
    employeeName: 'Sajid Mahmood',
    employeeId: 'EMP-2026-008',
    department: 'Construction Operations',
    branch: 'Jeddah',
    jobTitle: 'Welder',
    category: 'HR',
    requestType: 'Personal Data Change',
    requestDate: '2026-06-25',
    currentLevel: 2,
    currentLevelName: 'Level 1 – Direct Supervisor',
    currentApprover: 'Ahmed Faraj Al-Dossary (Supervisor)',
    status: 'Pending Approval',
    priority: 'Low',
    pendingDays: 0,
    slaLimitHours: 24,
    isFinancial: false,
    valueSAR: 0,
    details: 'Updating mobile number to +966 59 123 9988 and changing primary emergency contact details.',
    submissionDate: '2026-06-25',
    lastActionDate: '2026-06-25',
    history: [],
    formData: {
      mobileNew: '+966 59 123 9988',
      emergencyContactNew: 'Mahmood Ali (Father)'
    }
  },
  {
    id: 'REQ-2026-115',
    employeeName: 'Rajesh Subramanian Kumar',
    employeeId: 'EMP-2026-005',
    department: 'Engineering & Operations',
    branch: 'NEOM Site Office',
    jobTitle: 'Heavy Excavator Operator',
    category: 'HR',
    requestType: 'Contract Renewal Request',
    requestDate: '2026-06-20',
    currentLevel: 4,
    currentLevelName: 'Level 3 – Human Resources Department',
    currentApprover: 'Sarah Khalid Al-Ghamdi (HR Mgr)',
    status: 'Pending Approval',
    priority: 'High',
    pendingDays: 5,
    slaLimitHours: 48,
    isFinancial: true,
    valueSAR: 78000,
    details: 'Request for 1-year employment contract renewal with proposed 5% adjustment for outstanding performance index.',
    submissionDate: '2026-06-20',
    lastActionDate: '2026-06-22',
    history: [
      { level: 1, levelName: 'Level 1 – Direct Supervisor', approverName: 'Ahmed Faraj Al-Dossary', action: 'Approved', date: '2026-06-21', comment: 'Highly recommended. Top operator at site.' },
      { level: 2, levelName: 'Level 2 – Department Manager', approverName: 'Tariq Abdulaziz Al-Otaibi', action: 'Approved', date: '2026-06-22', comment: 'Approved on project budget.' }
    ],
    formData: {
      extensionDuration: '12 Months',
      proposedSalaryRaise: 5
    }
  },
  {
    id: 'REQ-2026-116',
    employeeName: 'John Michael Doe',
    employeeId: 'EMP-2026-007',
    department: 'Engineering & Operations',
    branch: 'NEOM Site Office',
    jobTitle: 'Lead Engineer',
    category: 'HR',
    requestType: 'Resignation Request',
    requestDate: '2026-06-19',
    currentLevel: 4,
    currentLevelName: 'Level 3 – Human Resources Department',
    currentApprover: 'Sarah Khalid Al-Ghamdi (HR Mgr)',
    status: 'Pending Approval',
    priority: 'Critical',
    pendingDays: 6,
    slaLimitHours: 72,
    isFinancial: false,
    valueSAR: 0,
    details: 'Official 30-day notice of resignation due to relocation opportunities in home country (UK).',
    submissionDate: '2026-06-19',
    lastActionDate: '2026-06-21',
    history: [
      { level: 1, levelName: 'Level 1 – Direct Supervisor', approverName: 'Ahmed Faraj Al-Dossary', action: 'Approved', date: '2026-06-20', comment: 'Regretfully recommended. Need replacement search immediately.' },
      { level: 2, levelName: 'Level 2 – Department Manager', approverName: 'Tariq Abdulaziz Al-Otaibi', action: 'Approved', date: '2026-06-21', comment: 'Initiated exit workflow.' }
    ],
    formData: {
      noticePeriodDays: 30,
      exitReason: 'Relocation to UK'
    }
  },
  {
    id: 'REQ-2026-117',
    employeeName: 'Faisal Ahmed Al-Harbi',
    employeeId: 'EMP-2026-004',
    department: 'Maintenance & Service',
    branch: 'Riyadh (HQ)',
    jobTitle: 'Senior Mechanic',
    category: 'HR',
    requestType: 'Transfer Request',
    requestDate: '2026-06-22',
    currentLevel: 4,
    currentLevelName: 'Level 3 – Human Resources Department',
    currentApprover: 'Sarah Khalid Al-Ghamdi (HR Mgr)',
    status: 'Pending Approval',
    priority: 'Medium',
    pendingDays: 3,
    slaLimitHours: 48,
    isFinancial: false,
    valueSAR: 0,
    details: 'Request to transfer permanently from Riyadh HQ Workshop to NEOM Site Support Depot due to site workload demands.',
    submissionDate: '2026-06-22',
    lastActionDate: '2026-06-23',
    history: [
      { level: 1, levelName: 'Level 1 – Direct Supervisor', approverName: 'Ahmed Faraj Al-Dossary', action: 'Approved', date: '2026-06-23', comment: 'Highly useful transfer. Approved.' },
      { level: 2, levelName: 'Level 2 – Department Manager', approverName: 'Tariq Abdulaziz Al-Otaibi', action: 'Approved', date: '2026-06-23', comment: 'Fills structural vacancy at NEOM depot.' }
    ],
    formData: {
      targetBranch: 'NEOM Site Office',
      targetDepartment: 'Maintenance & Service'
    }
  },
  {
    id: 'REQ-2026-118',
    employeeName: 'Ahmed Faraj Al-Dossary',
    employeeId: 'EMP-2026-006',
    department: 'Engineering & Operations',
    branch: 'Riyadh (HQ)',
    jobTitle: 'Supervisor',
    category: 'HR',
    requestType: 'Promotion Request',
    requestDate: '2026-06-17',
    currentLevel: 6,
    currentLevelName: 'Level 5 – General Manager (Final Approval)',
    currentApprover: 'Tariq Abdulaziz Al-Otaibi (General Manager)',
    status: 'Pending Approval',
    priority: 'High',
    pendingDays: 8,
    slaLimitHours: 72,
    isFinancial: true,
    valueSAR: 4500,
    details: 'Proposed promotion to Operations Assistant Director, citing 10 years of site safety management achievements.',
    submissionDate: '2026-06-17',
    lastActionDate: '2026-06-21',
    history: [
      { level: 1, levelName: 'Level 1 – Direct Supervisor', approverName: 'Tariq Abdulaziz Al-Otaibi', action: 'Approved', date: '2026-06-18', comment: 'Outstanding track record.' },
      { level: 2, levelName: 'Level 2 – Department Manager', approverName: 'Tariq Abdulaziz Al-Otaibi', action: 'Approved', date: '2026-06-19', comment: 'Strong recommendation.' },
      { level: 3, levelName: 'Level 3 – Human Resources Department', approverName: 'Sarah Khalid Al-Ghamdi', action: 'Approved', date: '2026-06-21', comment: 'Organization structure allows.' }
    ],
    formData: {
      proposedTitle: 'Operations Assistant Director',
      proposedSalaryRaise: 4500
    }
  },
  {
    id: 'REQ-2026-119',
    employeeName: 'John Michael Doe',
    employeeId: 'EMP-2026-007',
    department: 'Engineering & Operations',
    branch: 'NEOM Site Office',
    jobTitle: 'Lead Engineer',
    category: 'IT',
    requestType: 'New User Account',
    requestDate: '2026-06-25',
    currentLevel: 2,
    currentLevelName: 'Level 1 – Direct Supervisor',
    currentApprover: 'Ahmed Faraj Al-Dossary (Supervisor)',
    status: 'Pending Approval',
    priority: 'Medium',
    pendingDays: 0,
    slaLimitHours: 24,
    isFinancial: false,
    valueSAR: 0,
    details: 'Requesting Active Directory and enterprise email account creation for incoming site operator.',
    submissionDate: '2026-06-25',
    lastActionDate: '2026-06-25',
    history: [],
    formData: {
      newUserFullName: 'Rami Fahad Al-Mutairi',
      newUserRole: 'Operator',
      emailPreferred: 'rami.mutairi@almansoori.com'
    }
  },
  {
    id: 'REQ-2026-120',
    employeeName: 'Sarah Khalid Al-Ghamdi',
    employeeId: 'EMP-2026-002',
    department: 'Human Resources',
    branch: 'Riyadh (HQ)',
    jobTitle: 'Manager',
    category: 'Finance',
    requestType: 'Purchase Request',
    requestDate: '2026-06-24',
    currentLevel: 4,
    currentLevelName: 'Level 3 – Human Resources Department',
    currentApprover: 'Sarah Khalid Al-Ghamdi (HR Mgr)',
    status: 'Pending Approval',
    priority: 'High',
    pendingDays: 1,
    slaLimitHours: 48,
    isFinancial: true,
    valueSAR: 28500,
    details: 'Corporate purchasing requisition for replacement workstation laptops (5x Lenovo L14) for HR Department.',
    submissionDate: '2026-06-24',
    lastActionDate: '2026-06-24',
    history: [
      { level: 1, levelName: 'Level 1 – Direct Supervisor', approverName: 'Tariq Abdulaziz Al-Otaibi', action: 'Approved', date: '2026-06-24', comment: 'Approved. Laptops are outdated.' }
    ],
    formData: {
      itemDescription: 'Workstation laptops for HR staff',
      quantity: 5,
      unitPriceSAR: 5700
    }
  }
];
